### ISSUE TITLE
Multiple Time Series

### ISSUE THREAD

**Issue by Deepakgthomas** [statefb/dtwalign#1]
Would it be possible to extend this algorithm to take in multiple time series?

**Comment by statefb** [comment]
If you want to get just representative trajectory, consider following methods:  
* DTW barycenter averaging [github](https://github.com/fpetitjean/DBA)  
* soft-DTW [paper](https://arxiv.org/abs/1703.01541) [github](https://github.com/mblondel/soft-dtw)

or if you calculate multiple alignment, the best of my knowledge, there's no DTW based method but 
[Continuous profile modeling](http://www.cs.toronto.edu/~jenn/CPM/) should work, which method is based on HMM.
