### ISSUE TITLE
Problem with warping path creation

### ISSUE THREAD

**Issue by AgnieszkaMartyna-hybridLRproject** [statefb/dtwalign#11]
Dear Authors, 

I tried to apply your code for dtw along with R dtw package for comparison. My concerns arose when I got the same distance at the end between two aligned signals, but the warping paths were totally different (I have accounted for 0 and 1 start indexes in Python and R). I did it on my own on my data and it seems that the warping path is adequate in R but in Python something happens when it is retrieved from the end of the cumulative distance matrix as the step pattern is not maintained (or maybe the weights are not maintained, which are equal instead of e.g. 1-2-1 as in symmetric2 pattern). Thus the distance is well computed but the part with retrieving the path from the end seems to be wrong. Am  I right or if not, could you give me some explanation for the differences?

Thanks in advance
Agnieszka Martyna

**Comment by tonigi** [comment]
I would really need a reproducible example... thanks!

**Comment by tonigi** [comment]
Please also compare with the Python version of https://dynamictimewarping.github.io
