### ISSUE TITLE
Error when replicating example

### ISSUE THREAD

**Issue by jorgeverdu** [statefb/dtwalign#2]
When trying to replicate the example of local constraint:

res = dtw(x, y, step_pattern="symmetricP2")

This error appears:

 File "C:\Users\UB\Documents\research-jorge\venv\lib\site-packages\dtwalign\step_pattern.py", line 281, in __init__
    super().__init__()
TypeError: super() takes at least 1 argument (0 given)

**Comment by statefb** [comment]
I'm assuming that you are using python2.7. If so, consider update to upper than python3.5.
