### ISSUE TITLE
how to align n traces?

### ISSUE THREAD

**Issue by Qomo-CHENG** [statefb/dtwalign#4]
Thank you for this amazing package, it's helpful for my question.

I'm wondering how to align more than two traces? For example, by using the first trace as a reference, and to align the other n-1 traces. 

Thank you very much in advance!

**Comment by statefb** [comment]
Why don't you just repeat dtw for n-1 times as you mentioned?

**Comment by Qomo-CHENG** [comment]
> Why don't you just repeat dtw for n-1 times as you mentioned?

Thanks! I already finished by repeating dtw n-1 times, the results seem very good.
